[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "reactive-lib/=lib/reactive-lib/src/",
  "openzeppelin-contracts/=../evm/lib/openzeppelin-contracts/",
  "@openzeppelin/=../evm/lib/openzeppelin-contracts/",
]

allow_paths = ["lib/reactive-lib/src", "../evm/lib/openzeppelin-contracts"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
